# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_BSP = QtWidgets.QLabel(self.groupBox)
        self.label_BSP.setObjectName("label_BSP")
        self.horizontalLayout.addWidget(self.label_BSP)
        self.lineEdit_BSP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_BSP.setReadOnly(True)
        self.lineEdit_BSP.setObjectName("lineEdit_BSP")
        self.horizontalLayout.addWidget(self.lineEdit_BSP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_JetPack = QtWidgets.QLabel(self.groupBox)
        self.label_JetPack.setObjectName("label_JetPack")
        self.horizontalLayout_2.addWidget(self.label_JetPack)
        self.lineEdit_JetPack = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_JetPack.setReadOnly(True)
        self.lineEdit_JetPack.setObjectName("lineEdit_JetPack")
        self.horizontalLayout_2.addWidget(self.lineEdit_JetPack)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Camera = QtWidgets.QLabel(self.groupBox)
        self.label_Camera.setObjectName("label_Camera")
        self.horizontalLayout_3.addWidget(self.label_Camera)
        self.lineEdit_Camera = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Camera.setReadOnly(True)
        self.lineEdit_Camera.setObjectName("lineEdit_Camera")
        self.horizontalLayout_3.addWidget(self.lineEdit_Camera)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Information"))
        self.label_BSP.setText(_translate("MainWindow", "BSP:"))
        self.lineEdit_BSP.setText(_translate("MainWindow", "wait..."))
        self.label_JetPack.setText(_translate("MainWindow", "JetPack:"))
        self.lineEdit_JetPack.setText(_translate("MainWindow", "wait..."))
        self.label_Camera.setText(_translate("MainWindow", "Camera:"))
        self.lineEdit_Camera.setText(_translate("MainWindow", "wait..."))
